### ISSUE TITLE
Team ASCOL

### ISSUE THREAD

**Issue by roshangm1** [moz-np/Privacy_Campaign#2]
## Objective:

> Arguing that you don’t care about the right to privacy because you have nothing to hide is no different than saying you don’t care about free speech because you have nothing to say. 
- Edward Snowden

Our main objective would be making students understand why privacy really matters. 
## Key Results:
- [Measure of success 1 -- a good indication that you are making progress toward your objective] 
- [Measure of success 2 -- a good indication that you are making progress toward your objective] 
- [Measure of success 3 -- a good indication that you are making progress toward your objective] 
## Related Issues & Links:

[Reference meta issues, past issues or other people's issues if you might be working together] #
## Roles:

Who owns this plan: Roshan Gautam
Who is involved: Arjun Gautam, Prasanna Mishra
## Immediate next steps:
- [ ] First, put mittens on all of the kittens ([small, medium, large], Due: Feb 7th) 
- [ ] Second, put boots on all of the kittens ([small, medium, large], Due: Feb 7th) 
- [ ] Third, put hats on all of the kittens ([small, medium, large], Due: Feb 7th) 
#### Which campuses are potential participants in this campaign? Are these technical schools or liberal arts schools?
- Campuses with technical studies are the potential participants
#### Tasks you have completed
- [x] Registered in Mozillians.org
- [x] Registered as Firefox Student Ambassadors
- [x] Formed a Firefox Club in your college and registered it in the wiki.
- [ ] .....
- [ ] .....
